name: Build website with NodeJS and Gulp

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        gulp
    
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: .
        branch: gh-pages
        clean-exclude: pr-preview
        force: false