name: Preview/PR - Build website with NodeJS and Gulp

on:
  pull_request:
    branches: [ "main" ]
    # types:
    #   - opened
    #   - reopened
    #   - synchronize
    #   - closed
    
concurrency: preview-${{ github.ref }}
  
permissions:
  id-token: write # This is required for requesting the JWT
  contents: write # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        gulp

    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: .
    
